on:
  schedule:
    - cron:  '0 7 * * 3,6'
    # scheduled at 07:00 every Wednesday and Saturday

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync master with upstream latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v1
      with:
        upstream_repository: https://github.com/bitcoin/bitcoin
        upstream_branch: master

    - name: Timestamp
      run: date
