name: Sync Fork

on:
  schedule:
  - cron: '0 22 * * 2,6' # every Tuesday and Saturday at 10pm 
  workflow_dispatch: # on button click
jobs:
  sync: 
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: ${{ secrets.OZI_TOKEN }}
          owner: oziuzoma
          base: master
          head: master




        
