# name: Sync to Upstream
# on:
#   schedule:
#     - cron:  '0 17 * * 2,5'
#     # scheduled at 17:00 every Tuesday and Friday
#   workflow_dispatch:
# jobs:
#   sync_with_upstream:
#     runs-on: ubuntu-latest
#     name: Sync HEAD with upstream latest
#     steps:
#     # Step 1: run a standard checkout action, provided by github
#     - name: Checkout HEAD
#       uses: actions/checkout@v2
#       with:
#         ref: main
#     # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
#     - name: Pull upstream changes
#       id: sync
#       uses: oziuzoma/Fork-Sync-With-Upstream-action@v3.2
#       with:
#         upstream_repository: https://github.com/bitcoin/bitcoin
#         upstream_branch: main

name: Sync to Upstream

on:
  schedule:
    - cron:  '0 23 * * 3,6'
    # scheduled at 07:12 every Monday and Saturday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync HEAD with upstream latest

    steps:
    # Step 1: run a standard checkout action, provided by github
    - name: Checkout HEAD
      uses: actions/checkout@v2
      with:
        ref: main

    # Step 2: run this sync action - specify the upstream repo, upstream branch to sync with, and target sync branch
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      with:
        upstream_repository: https://github.com/bitcoin/bitcoin.git
        upstream_branch: main
        target_branch: main                      
        github_token: ${{ secrets.OZI_TOKEN }} 
